# Generated by Django 4.2.30 on 2026-07-26 17:26

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


COURSES = [
    {
        'slug': 'blues-foundations',
        'name': 'Blues Guitar Foundations',
        'category': 'Course',
        'description': (
            'Shuffle rhythm, turnarounds, pentatonic phrasing, and practice '
            'tracks for building a stronger blues vocabulary.'
        ),
        'price': Decimal('49.00'),
        'display_order': 10,
    },
    {
        'slug': 'jazz-chords',
        'name': 'Jazz Chord Starter Pack',
        'category': 'Song Pack',
        'description': (
            'Playable chord shapes, comping studies, and lead sheets for '
            'common jazz progressions.'
        ),
        'price': Decimal('35.00'),
        'display_order': 20,
    },
    {
        'slug': 'private-session',
        'name': 'Private Learning Session',
        'category': 'Lesson',
        'description': (
            'A focused one-on-one session for technique, repertoire, ear '
            'training, improvisation, or recording questions.'
        ),
        'price': Decimal('75.00'),
        'display_order': 30,
    },
]


def seed_courses(apps, schema_editor):
    Course = apps.get_model('pages', 'Course')
    for course in COURSES:
        Course.objects.update_or_create(
            slug=course['slug'],
            defaults={
                'name': course['name'],
                'category': course['category'],
                'description': course['description'],
                'price': course['price'],
                'display_order': course['display_order'],
                'is_available': True,
            },
        )


def remove_seed_courses(apps, schema_editor):
    Course = apps.get_model('pages', 'Course')
    Course.objects.filter(slug__in=[course['slug'] for course in COURSES]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('category', models.CharField(default='Course', max_length=80)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_available', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.RunPython(seed_courses, reverse_code=remove_seed_courses),
    ]
